### PR TITLE
fix: upgrade semantic-release dependencies

### PR DESCRIPTION
**Pull request by fgreinacher**
BREAKING CHANGES:

- This package is not compatible with semantic-release < 20.1.0.
- The minimum supported Node version has been changed to 18.0.0.

### CODE REVIEW

**Comment by travi** [comment]
> cannot be used by CJS packages

this might be slightly misleading. the consuming project itself can still be CJS, but the way semantic-release consumes this would need to follow ESM. since semantic-release is its own executable independent of the consuming project, that is fine from an ESM perspective as long as the project's release config is either using a .mjs extension or uses a non-js formatted config file.

however, that starts to step into the territory of this issue: https://github.com/semantic-release/semantic-release/discussions/2686

in addition, we deferred some of the complexities of loading esm configs that are extended within a project's config with the initial ESM conversion of core. this is our first case that might need to motivate us to push through that functionality.

it is good that we are starting with a pre-release here as i imagine that we will have some things to figure out about supported ways to consume this. if you have the time/energy to explore some of those, please feel free.

**Review by travi — APPROVED** [review]

**Comment by travi** [comment]
Please feel free to move forward with testing this out. I'm stepping away for a couple of weeks, but hoping that I won't be a blocker on this

**Comment by fgreinacher** [comment]
I got derailed from this.

My main goal here was to unblock the upgrades in https://github.com/semantic-release/gitlab-config/pull/198.

@travi Would it be enough to stick with CJS, get rid of `xo` and upgrade the minimum Node version?

**Comment by travi** [comment]
> Would it be enough to stick with CJS, get rid of `xo` and upgrade the minimum Node version?

i think that should work just fine. lets give it a shot and make sure there are no surprises 👍🏼

**Comment by fgreinacher** [comment]
> > Would it be enough to stick with CJS, get rid of `xo` and upgrade the minimum Node version?
> 
> i think that should work just fine. lets give it a shot with a beta release and make sure there are no surprises 👍🏼

Looking good. I'll go ahead merge this to `beta`.

**Pull request merged**
